app/package-lock.json
app/src/models/JetTypes.ts
app/src/scripts/jet.ts
app/src/scripts/programUtil.ts
app/src/scripts/subscribe.ts
app/src/views/Cockpit.svelte
libraries/ts/src/index.ts
package-lock.json

Removing 3 position limit.
Refreshing all reserves regardless of any position.
Console logging an explorer link.
No longer refreshing after an airdrop. 'Reload' button to confirm changed to 'Okay'
Update c-ratio as per Logans suggestion
Associated token accounts everywhere (almost)

Split transactions

---

app/src/scripts/localization.ts

Check if country is Ukraine, then checks if postal code matches Crimean postal codes.

let Ukraine in

---

app/public/global.css
app/src/components/ReserveDetail.svelte
app/src/scripts/localization.ts
app/src/views/Cockpit.svelte

Minimum C-Ratio rather than Maximum LTV

min-c-ratio-definition

---

app/public/global.css
app/public/index.html
app/public/manifest.json
app/src/components/ReserveDetail.svelte
app/src/scripts/jet.ts
app/src/scripts/localization.ts
app/src/views/Cockpit.svelte

hard code min c-ratio to 130 for devnet
warn  user if trade lowers c-ratio between 130-140
fix withdraw disabling for no asset collateral

Min Ratio UI Adjustments

---

app/src/models/JetTypes.ts
app/src/scripts/jet.ts

fix datatable search input (.toString() of undefined)

fix search input

---

app/.env.sample
app/public/index.html
app/rollup.config.js

New Devops (switch from Firebase to Netlify)
Update .env.sample for development server
Merge Tristyn's new PR on master

Frontend Merge

---

app/src/scripts/localization.ts

- Fixed bug in Crimea check code
- Moved checker to helper function

Moved Crimea check to helper

---

programs/jet/src/state/obligation.rs

Removing the limitation that prevents a user from borrowing an asset that they also have deposited as collateral, as there's not really any risk to the program in allowing this.

remove limitation on having loan/collateral on same asset

---

app/src/views/Cockpit.svelte

Fixed large negative C-ratio in repay

---

programs/jet/src/instructions/close_deposit_account.rs
programs/jet/src/instructions/liquidate.rs
programs/jet/src/state/obligation.rs
programs/jet/src/state/reserve.rs

- fix more bad accounting
- also add some extra unit tests for liquidations

more accounting fixes

---

app/src/scripts/utils.ts

Fixes withdrawing a max balance of ~10 lamports

Can enter an exponential string like 7.46e-7 as a token amount

---

app/package-lock.json
app/src/scripts/jet.ts
app/src/scripts/subscribe.ts

check for mainnet before warning

---

app/src/components/TradePanel.svelte

am I doing this right? for branch name and commit message to link to Jira

JET-192 fix input zero or negative zero

---

libraries/math/src/number.rs
programs/jet/src/instructions/borrow.rs
programs/jet/src/instructions/init_market.rs
programs/jet/src/instructions/init_reserve.rs
programs/jet/src/instructions/liquidate.rs
programs/jet/src/instructions/liquidate_dex.rs
programs/jet/src/instructions/withdraw_collateral.rs
programs/jet/src/lib.rs
programs/jet/src/state/market.rs
programs/jet/src/state/obligation.rs
programs/jet/src/state/reserve.rs
programs/test-writer/src/lib.rs

fixed a bunch of clippy lints while skimming the codebase.

chore(clippy): clippy --fix

---

programs/jet/src/state/obligation.rs

Add a minimum value, under which there's no constraint that a partial
amount of the collateral is liquidated. This is useful to prevent cases
where accounts are slowly liquidated to a point where the remaining
balances are too small and get rounded to zero when attempting to repay
via liquidation.

JET-147: hardcode minimum for partial liquidations

---

app/public/global.css
app/src/components/Button.svelte
app/src/components/ConnectWalletModal.svelte
app/src/components/Copilot.svelte
app/src/components/InitFailed.svelte
app/src/components/Input.svelte
app/src/components/Loader.svelte
app/src/components/Logo.svelte
app/src/components/Nav.svelte
app/src/components/PercentageChart.svelte
app/src/components/ReserveDetail.svelte
app/src/components/TradePanel.svelte
app/src/views/Cockpit.svelte
app/src/views/Settings.svelte
app/src/views/TransactionLogs.svelte

fix mobile response window and market table accordingly

Fix mobile response

---

app/src/App.svelte
app/src/components/Copilot.svelte

This reverts commit 1cb506bca2b3d4446731cabe51e501d2bc89b32f.

Revert "mainnet network warning (#362)"

---

.github/workflows/build.yml

- remove rust installation, should be already installed

fix build tool setup in ci

---

.github/workflows/build.yml

fix ci deps

---

app/src/scripts/languages/Jet_Definitions_IT.json
app/src/scripts/languages/Jet_UI_IT.json
app/src/scripts/localization.ts

Added Italian translations. All front end was translated to Italian that is my main language. It was tested and stable

Added Italian translations

---

programs/jet/src/state/obligation.rs

Existing code may miss positions in the list after an entry that was
previously removed. Updating the method of accessing the position to
always go through `iter` function, which will provide an iterator of
the correct positions.

always use `iter` for accessing position list

---

.github/workflows/build.yml

adds clippy to existing github flow

github action with clippy

---

Cargo.lock
Cargo.toml
libraries/cpi/Cargo.toml
libraries/cpi/src/accounts.rs
libraries/cpi/src/errors.rs
libraries/cpi/src/instruction.rs
libraries/cpi/src/lib.rs
programs/jet/src/instructions/withdraw_collateral.rs

Add a library for interfacing with the jet program from anchor `v0.21.0`

add a CPI library for newer anchor programs to link with

---

README.md

Add a note to the README that this repository is deprecated

Update note in README
